
CREATE DATABASE DB_SCOLASTICC
GO
USE  DB_SCOLASTICC
GO

CREATE  TABLE ALUNO
(
	PK_CD_ALUNO INT IDENTITY(1,1) NOT NULL,
	NM_ALUNO VARCHAR(60) NOT NULL,
	RG_ALUNO VARCHAR(60) NOT NULL,
	CPF_ALUNO VARCHAR(60) UNIQUE NOT NULL,
	SEXO_ALUNO VARCHAR(60) NOT NULL,
	NM_CIDADE VARCHAR (60) NOT NULL,
	END_CIDADE VARCHAR (60) NOT NULL,
	END_BAIRRO VARCHAR (60) NOT NULL,
	CEP_CIDADE VARCHAR(60),
	NR_TELEFONE VARCHAR(60),
	DS_EMAIL VARCHAR (60),
	DT_NASCIMENTO DATETIME NOT NULL,
	CONSTRAINT PK_CD_ALUNO PRIMARY KEY(PK_CD_ALUNO)
	
)
GO

INSERT INTO ALUNO VALUES ('MARCOS LIMA','6764776-45','1234678-91','M','RIO DE JANEIRO','AV DAS AMERICAS','BARRA','20587-87','(21) 2387-7645','BACHAREL@TECNOLOGIA','2001-11-10')
INSERT INTO ALUNO VALUES ('CARLOS SILVA','6764776-45','1234678-92','M','RIO DE JANEIRO','AV DAS AMERICAS','BARRA','20587-87','(21) 2387-7645','BACHAREL@TECNOLOGIA','2001-11-10')
INSERT INTO ALUNO VALUES ('RONALDO CABRAL','6764776-45','1234678-93','M','RIO DE JANEIRO','AV DAS AMERICAS','BARRA','20587-87','(21) 2387-7645','BACHAREL@TECNOLOGIA','2001-11-10')

GO

CREATE PROCEDURE INSERE_ALUNO
    @PK_CD_ALUNO INT OUTPUT,
     @NM_ALUNO VARCHAR (60),
     @RG_ALUNO VARCHAR(60),
	 @CPF_ALUNO VARCHAR(60),
	 @SEXO_ALUNO VARCHAR(25),
	 @NM_CIDADE VARCHAR (60),
	 @END_CIDADE VARCHAR (60),
	 @END_BAIRRO VARCHAR (60),
	 @CEP_CIDADE VARCHAR(60),
	 @NR_TELEFONE VARCHAR(60),
	 @DS_EMAIL VARCHAR (60),
	 @DT_NASCIMENTO DATETIME 
AS

     INSERT INTO ALUNO(
    NM_ALUNO,
    RG_ALUNO,
	CPF_ALUNO,
	SEXO_ALUNO,
	NM_CIDADE,
	END_CIDADE,
	END_BAIRRO,
	CEP_CIDADE,
	NR_TELEFONE,
	DS_EMAIL,
	DT_NASCIMENTO)
     VALUES(
     @NM_ALUNO,
     @RG_ALUNO,
	 @CPF_ALUNO,
	 @SEXO_ALUNO,
	 @NM_CIDADE,
	 @END_CIDADE,
	 @END_BAIRRO ,
	 @CEP_CIDADE,
	 @NR_TELEFONE,
	 @DS_EMAIL,
	 @DT_NASCIMENTO)

     SET @PK_CD_ALUNO = (SELECT @@IDENTITY)
GO
   -- declare @PK_CD_ALUNO int
	--execute INSERE_ALUNO @pk_cd_aluno output,'JOSE ANDRADE','6764776-45','1234678-94','M','RIO DE JANEIRO','AV DAS AMERICAS','BARRA','20587-87','(21) 2387-7645','BACHAREL@TECNOLOGIA','2001-11-10'

GO
CREATE  PROCEDURE ALTERA_ALUNO
    @PK_CD_ALUNO INT OUTPUT,
     @NM_ALUNO VARCHAR(60),
	 @RG_ALUNO VARCHAR(60),
	 @CPF_ALUNO VARCHAR(60),
	 @SEXO_ALUNO VARCHAR(25),
	 @NM_CIDADE VARCHAR (60),
	 @END_CIDADE VARCHAR (60),
	 @END_BAIRRO VARCHAR (60),
	 @CEP_CIDADE VARCHAR(60),
	 @NR_TELEFONE VARCHAR(60),
	 @DS_EMAIL VARCHAR (60),
	 @DT_NASCIMENTO DATETIME
    
AS

     UPDATE ALUNO 
     SET NM_ALUNO = @NM_ALUNO,
		 RG_ALUNO = @RG_ALUNO,
		 CPF_ALUNO = @CPF_ALUNO,
	     SEXO_ALUNO = @SEXO_ALUNO,
		 NM_CIDADE = @NM_CIDADE,
		 END_CIDADE = @END_CIDADE,
	     END_BAIRRO = @END_BAIRRO,
		 CEP_CIDADE = @CEP_CIDADE,
	     NR_TELEFONE = @NR_TELEFONE,
		 DS_EMAIL = @DS_EMAIL,
		DT_NASCIMENTO = @DT_NASCIMENTO
     WHERE PK_CD_ALUNO = @PK_CD_ALUNO
	----------------------------------------------
  GO
 
CREATE PROCEDURE EXCLUI_ALUNO
     @PK_CD_ALUNO INT -- INTPUT
AS    
     DELETE FROM ALUNO
     WHERE PK_CD_ALUNO = @PK_CD_ALUNO
	execute EXCLUI_ALUNO 9
GO
CREATE PROCEDURE SELECIONA_ALUNO
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM ALUNO
     ELSE      
        SELECT * FROM ALUNO
        WHERE NM_ALUNO LIKE '%' + @FILTRO + '%'
           OR CPF_ALUNO LIKE '%' + @FILTRO + '%'
           
END


GO
GO

CREATE TABLE PROFESSOR
(
	PK_CD_PROFESSOR INT IDENTITY(1,1) NOT NULL,
	NM_PROFESSOR VARCHAR(60) NOT NULL,
	RG_PROFESSOR VARCHAR(60) NOT NULL,
	CPF_PROFESSOR VARCHAR(60) UNIQUE NOT NULL,
	SEXO_PROFESSOR CHAR,
	NM_CIDADE VARCHAR (60),
	END_CIDADE VARCHAR (60),
	END_BAIRRO VARCHAR (60),
	CEP_CIDADE VARCHAR(60),
	NR_TELEFONE VARCHAR(60),
	TITULO_ACADEMICO VARCHAR(60),
	DS_EMAIL VARCHAR (60),
	DT_NASCIMENTO DATETIME NOT NULL,
	CONSTRAINT PK_CD_PROFESSOR PRIMARY KEY(PK_CD_PROFESSOR),
)
GO
INSERT INTO PROFESSOR VALUES ('RICARDO SOUZA','6764776-45','1234678-91','M','RIO DE JANEIRO','AV DAS AMERICAS','BARRA','20587-87','(21) 2387-7645','MATEMATICO','BACHAREL@TECNOLOGIA','2001-11-10')
INSERT INTO PROFESSOR VALUES ('LUCAS MENDES','6764776-45','1234678-92','M','RIO DE JANEIRO','AV DAS AMERICAS','BARRA','20587-87','(21) 2387-7645','LINGUAS','BACHAREL@TECNOLOGIA','2001-11-10')
GO

CREATE  PROCEDURE INSERE_PROFESSOR
     @PK_CD_PROFESSOR INT OUTPUT,
     @NM_PROFESSOR VARCHAR(60),
	 @RG_PROFESSOR VARCHAR(60),
	 @CPF_PROFESSOR VARCHAR(60),
	 @SEXO_PROFESSOR CHAR,
	 @NM_CIDADE VARCHAR (60),
	 @END_CIDADE VARCHAR (60),
	 @END_BAIRRO VARCHAR (60),
	 @CEP_CIDADE VARCHAR(60),
	 @NR_TELEFONE VARCHAR(60),
	 @TITULO_ACADEMICO VARCHAR (60),
	 @DS_EMAIL VARCHAR (60),
	 @DT_NASCIMENTO DATETIME 
AS

     INSERT INTO PROFESSOR(NM_PROFESSOR,
	RG_PROFESSOR,
	CPF_PROFESSOR,
	SEXO_PROFESSOR,
	NM_CIDADE,
	END_CIDADE,
	END_BAIRRO,
	CEP_CIDADE,
	NR_TELEFONE,
	TITULO_ACADEMICO,
	DS_EMAIL,
	DT_NASCIMENTO)
     VALUES(@NM_PROFESSOR, 
     @RG_PROFESSOR,
	 @CPF_PROFESSOR,
	 @SEXO_PROFESSOR,
	 @NM_CIDADE,
	 @END_CIDADE,
	 @END_BAIRRO ,
	 @CEP_CIDADE,
	 @NR_TELEFONE,
	 @TITULO_ACADEMICO,
	 @DS_EMAIL,
	 @DT_NASCIMENTO )

     SET @PK_CD_PROFESSOR = (SELECT @@IDENTITY)
-------------------------------------------------
 GO


CREATE  PROCEDURE ALTERA_PROFESSOR
    @PK_CD_PROFESSOR INT OUTPUT,
     @NM_PROFESSOR VARCHAR(60),
	  @RG_PROFESSOR VARCHAR(60),
	 @CPF_PROFESSOR VARCHAR(60),
	 @SEXO_PROFESSOR CHAR,
	 @NM_CIDADE VARCHAR (60),
	 @END_CIDADE VARCHAR (60),
	 @END_BAIRRO VARCHAR (60),
	 @CEP_CIDADE VARCHAR(60),
	 @NR_TELEFONE VARCHAR(60),
	 @TITULO_ACADEMICO VARCHAR(60),
	 @DS_EMAIL VARCHAR (60),
	 @DT_NASCIMENTO DATETIME
    
AS

     UPDATE PROFESSOR 
     SET NM_PROFESSOR = @NM_PROFESSOR,
		 RG_PROFESSOR = @RG_PROFESSOR,
		 CPF_PROFESSOR = @CPF_PROFESSOR,
	     SEXO_PROFESSOR = @SEXO_PROFESSOR,
		 NM_CIDADE = @NM_CIDADE,
		 END_CIDADE = @END_CIDADE,
	     END_BAIRRO = @END_BAIRRO,
		 CEP_CIDADE = @CEP_CIDADE,
	     NR_TELEFONE = @NR_TELEFONE,
		 TITULO_ACADEMICO = @TITULO_ACADEMICO,
		 DS_EMAIL = @DS_EMAIL,
		 DT_NASCIMENTO = @DT_NASCIMENTO 
     WHERE PK_CD_PROFESSOR = @PK_CD_PROFESSOR
 
GO

CREATE PROCEDURE EXCLUI_PROFESSOR
     @PK_CD_PROFESSOR INT -- INTPUT
AS    
     DELETE FROM PROFESSOR
     WHERE PK_CD_PROFESSOR = @PK_CD_PROFESSOR
	
GO


CREATE PROCEDURE SELECIONA_PROFESSOR
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM PROFESSOR
     ELSE      
        SELECT * FROM PROFESSOR
        WHERE NM_PROFESSOR LIKE '%' + @FILTRO + '%'
           OR CPF_PROFESSOR LIKE '%' + @FILTRO + '%'
           
END
---------------------------------
execute SELECIONA_PROFESSOR 43
GO

CREATE TABLE CURSO
(
	PK_CD_CURSO INT IDENTITY(1,1) NOT NULL,
	NM_CURSO VARCHAR(60) NOT NULL,
	DURACAO_CURSO_TOTAL VARCHAR(60) NOT NULL,
	CONSTRAINT PK_CD_CURSO PRIMARY KEY(PK_CD_CURSO),
	
)
GO

INSERT INTO CURSO VALUES ('ENSINO FUNDAMENTAL','500 HORAS')
GO

CREATE PROCEDURE INSERE_CURSO
     @PK_CD_CURSO INT OUTPUT,
     @NM_CURSO VARCHAR(60), 
     @DURACAO_CURSO_TOTAL VARCHAR(60)
	 
AS

     INSERT INTO CURSO(NM_CURSO,DURACAO_CURSO_TOTAL)
     VALUES(@NM_CURSO,@DURACAO_CURSO_TOTAL)

     SET @PK_CD_CURSO = (SELECT @@IDENTITY)

GO


CREATE PROCEDURE ALTERA_CURSO
     @PK_CD_CURSO INT, -- INTPUT
     @NM_CURSO VARCHAR(60), -- INTPUT
     @DURACAO_CURSO_TOTAL VARCHAR(60)
	     
AS

     UPDATE CURSO 
     SET NM_CURSO = @NM_CURSO,
		 DURACAO_CURSO_TOTAL = @DURACAO_CURSO_TOTAL	
     WHERE PK_CD_CURSO = @PK_CD_CURSO 
-----------------------------------------

GO

CREATE  PROCEDURE EXCLUI_CURSO
     @PK_CD_CURSO INT 
AS    
     DELETE FROM CURSO
     WHERE PK_CD_CURSO = @PK_CD_CURSO
	
	execute EXCLUI_CURSO 1
----------------------------
GO

CREATE PROCEDURE SELECIONA_CURSO
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM CURSO
     ELSE      
        SELECT * FROM CURSO
        WHERE NM_CURSO LIKE '%' + @FILTRO + '%'
           --OR DT_CURSO LIKE '%' + @FILTRO + '%'
           
END
GO

CREATE TABLE TURMA
(
    PK_CD_TURMA INT IDENTITY(1,1) NOT NULL,
	NM_TURMA VARCHAR(60) NOT NULL,
	TURNO VARCHAR(60) NOT NULL,
	ANO VARCHAR(40) NOT NULL,
	FKI_CD_CURSO INT NOT NULL,
	CONSTRAINT PK_CD_TURMA PRIMARY KEY(PK_CD_TURMA),
	CONSTRAINT FKI_CD_CURSO FOREIGN KEY(FKI_CD_CURSO) REFERENCES CURSO(PK_CD_CURSO)
	
)
GO

INSERT INTO TURMA VALUES ('SEG A','TARDE','2023',1)
GO

CREATE PROCEDURE INSERE_TURMA
     @PK_CD_TURMA INT OUTPUT,
     @NM_TURMA VARCHAR(60),
	 @TURNO VARCHAR(60),
     @ANO VARCHAR(60),
	 @FKI_CD_CURSO INT
AS

     INSERT INTO TURMA(NM_TURMA,TURNO,ANO,FKI_CD_CURSO)
     VALUES(@NM_TURMA,@TURNO,@ANO,@FKI_CD_CURSO)

     SET @PK_CD_TURMA = (SELECT @@IDENTITY)
--------------------------------
GO

CREATE PROCEDURE ALTERA_TURMA
     @PK_CD_TURMA INT OUTPUT,
     @NM_TURMA VARCHAR(60),
	 @TURNO VARCHAR(60),
     @ANO VARCHAR(60),
	 @FKI_CD_CURSO INT
    
AS

     UPDATE TURMA 
     SET NM_TURMA = @NM_TURMA,
		 TURNO = @TURNO,
		 ANO = @ANO,
		 FKI_CD_CURSO = @FKI_CD_CURSO
     WHERE PK_CD_TURMA = @PK_CD_TURMA 
	
GO

CREATE PROCEDURE EXCLUI_TURMA
     @PK_CD_TURMA INT -- INTPUT
AS    
     DELETE FROM TURMA
     WHERE PK_CD_TURMA = @PK_CD_TURMA
	

GO

CREATE PROCEDURE SELECIONA_TURMA
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM TURMA

     ELSE      
      
		SELECT TURMA.PK_CD_TURMA AS "CODIGO TURMA", TURMA.NM_TURMA AS TURMA, TURMA.TURNO AS PERIODO, TURMA.ANO AS ANO,CURSO.NM_CURSO as CURSO, CURSO.PK_CD_CURSO as "CODIGO CURSO" 
		FROM TURMA 
		INNER JOIN CURSO ON TURMA.FKI_CD_CURSO = CURSO.PK_CD_CURSO
	      WHERE TURMA.NM_TURMA LIKE '%' + @FILTRO + '%'
                
END

GO

CREATE TABLE DISCIPLINA
(
	PK_CD_DISCIPLINA INT IDENTITY(1,1) NOT NULL,
	NM_DISCIPLINA VARCHAR(100) NOT NULL,
	CARGA_HORARIA_DS VARCHAR(60),
	FK_CD_PROFESSOR INT NOT NULL,
	FKI_CD_TURMA INT NOT NULL,
	CONSTRAINT PK_CD_DISCIPLINA PRIMARY KEY(PK_CD_DISCIPLINA),
	CONSTRAINT FK_CD_PROFESSOR FOREIGN KEY(FK_CD_PROFESSOR) REFERENCES PROFESSOR(PK_CD_PROFESSOR),
	CONSTRAINT FKI_CD_TURMA FOREIGN KEY(FKI_CD_TURMA) REFERENCES TURMA(PK_CD_TURMA)
	
)
GO
INSERT INTO DISCIPLINA VALUES ('MATEMATICA','86 HORAS',1,1)
GO

CREATE PROCEDURE INSERE_DISCIPLINA
     @PK_CD_DISCIPLINA INT OUTPUT,
     @NM_DISCIPLINA VARCHAR(100),
	 @CARGA_HORARIA_DS VARCHAR(60),
	 @FK_CD_PROFESSOR INT,
	 @FKI_CD_TURMA INT
AS

     INSERT INTO DISCIPLINA(NM_DISCIPLINA,CARGA_HORARIA_DS,FK_CD_PROFESSOR,FKI_CD_TURMA)
     VALUES(@NM_DISCIPLINA,@CARGA_HORARIA_DS,@FK_CD_PROFESSOR,@FKI_CD_TURMA)

     SET @PK_CD_DISCIPLINA = (SELECT @@IDENTITY)
GO

CREATE PROCEDURE ALTERA_DISCIPLINA
     @PK_CD_DISCIPLINA INT, -- INTPUT
     @NM_DISCIPLINA VARCHAR(100), -- INTPUT
     @CARGA_HORARIA_DS VARCHAR(60),
	 @FK_CD_PROFESSOR INT,
	  @FKI_CD_TURMA INT
AS

     UPDATE DISCIPLINA
     SET NM_DISCIPLINA = @NM_DISCIPLINA,
		 CARGA_HORARIA_DS = @CARGA_HORARIA_DS,
		 FK_CD_PROFESSOR = @FK_CD_PROFESSOR,
		 FKI_CD_TURMA =  @FKI_CD_TURMA
		  WHERE PK_CD_DISCIPLINA = @PK_CD_DISCIPLINA

GO

CREATE PROCEDURE EXCLUI_DISCIPLINA
                @PK_CD_DISCIPLINA INT -- INTPUT
AS    
     DELETE FROM DISCIPLINA
     WHERE PK_CD_DISCIPLINA = @PK_CD_DISCIPLINA
GO

CREATE PROCEDURE SELECIONA_DISCIPLINA
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM DISCIPLINA
     ELSE      
        SELECT * FROM DISCIPLINA
        WHERE NM_DISCIPLINA LIKE '%' + @FILTRO + '%'
           
END
GO
--SELECT * FROM DISCIPLINA
CREATE PROCEDURE SELECIONA_DISCIPLINAL
     @FILTRO VARCHAR(100) = NULL,
	 @FK_CD_PROFESSOR INT
AS 
BEGIN
     IF @FILTRO IS NULL
         SELECT * FROM DISCIPLINA
        WHERE NM_DISCIPLINA  LIKE '%' + @FILTRO + '%'  AND FK_CD_PROFESSOR = @FK_CD_PROFESSOR
     ELSE      
        SELECT * FROM DISCIPLINA
        WHERE NM_DISCIPLINA  LIKE '%' + @FILTRO + '%'  AND FK_CD_PROFESSOR = @FK_CD_PROFESSOR
           
END
GO


CREATE TABLE MATRICULA
(
    PK_CD_MATRICULA INT IDENTITY(1,1) NOT NULL,
	FK_CD_ALUNO INT NOT NULL,
	FK_CD_TURMA INT NOT NULL,
	FK_CD_CURSO INT NOT NULL,
	NM_ALUNOM  VARCHAR(60),
	CONSTRAINT PK_CD_MATRICULA PRIMARY KEY(PK_CD_MATRICULA),
	CONSTRAINT FK_CD_ALUNO FOREIGN KEY(FK_CD_ALUNO) REFERENCES ALUNO(PK_CD_ALUNO),
	CONSTRAINT FK_CD_TURMA FOREIGN KEY(FK_CD_TURMA) REFERENCES TURMA(PK_CD_TURMA),
	CONSTRAINT FK_CD_CURSO FOREIGN KEY(FK_CD_CURSO) REFERENCES CURSO(PK_CD_CURSO)
)
GO
INSERT INTO MATRICULA VALUES (1,1,1,'MARCOS LIMA')
GO


CREATE  PROCEDURE INSERE_MATRICULA
     @PK_CD_MATRICULA INT OUTPUT,
	 @FK_CD_ALUNO INT,
     @FK_CD_TURMA INT, 
     @FK_CD_CURSO INT,
	 @NM_ALUNOM  VARCHAR (60)
	
AS

     INSERT INTO MATRICULA(FK_CD_ALUNO, FK_CD_TURMA,FK_CD_CURSO,NM_ALUNOM)
     VALUES(@FK_CD_ALUNO, @FK_CD_TURMA,@FK_CD_CURSO,@NM_ALUNOM)

     SET @PK_CD_MATRICULA = (SELECT @@IDENTITY)
-------------------------------------------
GO

CREATE  PROCEDURE ALTERA_MATRICULA
     @PK_CD_MATRICULA INT OUTPUT,
	 @FK_CD_ALUNO INT,
     @FK_CD_TURMA INT, 
	 @FK_CD_CURSO INT,
	 @NM_ALUNOM  VARCHAR
    
AS

     UPDATE MATRICULA 
     SET FK_CD_ALUNO = @FK_CD_ALUNO,
		 FK_CD_TURMA = @FK_CD_TURMA,
		 FK_CD_CURSO = @FK_CD_CURSO,
		 NM_ALUNOM =  @NM_ALUNOM 
		 
     WHERE PK_CD_MATRICULA = @PK_CD_MATRICULA 
GO

CREATE  PROCEDURE EXCLUI_MATRICULA
     @PK_CD_MATRICULA INT
	  
AS    
     DELETE FROM MATRICULA
     WHERE PK_CD_MATRICULA = @PK_CD_MATRICULA
	

GO

CREATE PROCEDURE SELECIONA_MATRICULA
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM MATRICULA
		
     ELSE      
     
		SELECT ALUNO.PK_CD_ALUNO AS "CODIGO ALUNO", ALUNO.NM_ALUNO AS "NOME ALUNO",MATRICULA.PK_CD_MATRICULA AS "CODIGO DA MATRICULA", MATRICULA.FK_CD_TURMA AS "CODIGO TURMA",MATRICULA.FK_CD_CURSO " CODIGO CURSO", CURSO.NM_CURSO AS CURSO, TURMA.NM_TURMA AS TURMA 
		FROM MATRICULA 
		INNER JOIN ALUNO ON MATRICULA.FK_CD_ALUNO = ALUNO.PK_CD_ALUNO
		INNER JOIN CURSO ON CURSO.PK_CD_CURSO = MATRICULA.FK_CD_CURSO
		INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
		 WHERE NM_ALUNO LIKE '%' + @FILTRO + '%'

           
END
GO



CREATE TABLE AVALIATION
(
	PK_CD_AVALIATION INT IDENTITY(1,1) NOT NULL,
	DAT DATETIME,
	FREQUNCIA CHAR,
	FKI_CD_MATRICULA INT NOT NULL,
	FKI_CD_DISCIPLINA INT NOT NULL,
	
	CONSTRAINT PK_CD_AVALIATION PRIMARY KEY(PK_CD_AVALIATION),
	CONSTRAINT FKI_CD_MATRICULA FOREIGN KEY(FKI_CD_MATRICULA) REFERENCES MATRICULA(PK_CD_MATRICULA),
	CONSTRAINT FKI_DISCIPLINA FOREIGN KEY(FKI_CD_DISCIPLINA) REFERENCES DISCIPLINA(PK_CD_DISCIPLINA),
	
)
GO

INSERT INTO AVALIATION VALUES ('2001-11-10','P',1,1)
GO

CREATE  PROCEDURE INSERE_AVALIATION
     @PK_CD_AVALIATION INT OUTPUT,
     @DAT DATETIME,
	 @FREQUNCIA CHAR,
	 @FKI_CD_MATRICULA INT,
	 @FKI_CD_DISCIPLINA INT
	
AS

     INSERT INTO AVALIATION(DAT,FREQUNCIA,FKI_CD_MATRICULA,FKI_CD_DISCIPLINA)
     VALUES(@DAT,@FREQUNCIA, @FKI_CD_MATRICULA,@FKI_CD_DISCIPLINA)

     SET @PK_CD_AVALIATION = (SELECT @@IDENTITY)
GO
   

CREATE PROCEDURE ALTERA_AVALIATION
     @PK_CD_AVALIATION INT OUTPUT,
     @DAT DATETIME,
	 @FREQUNCIA CHAR,
	 @FKI_CD_MATRICULA INT,
	 @FKI_CD_DISCIPLINA INT
    
AS

     UPDATE AVALIATION 
     SET  
			FREQUNCIA = @FREQUNCIA,
			   DAT = @DAT
     WHERE PK_CD_AVALIATION =@PK_CD_AVALIATION
	
GO

CREATE PROCEDURE EXCLUI_AVALIATION
     @PK_CD_AVALIATION INT -- INTPUT
AS    
     DELETE FROM AVALIATION
     WHERE PK_CD_AVALIATION = @PK_CD_AVALIATION
GO

CREATE PROCEDURE SELECIONA_AVALIATION
     @FILTRO VARCHAR(100) 
	 
AS 
BEGIN
     IF @FILTRO IS NULL 
	    SELECT  MATRICULA.NM_ALUNOM, MATRICULA.PK_CD_MATRICULA as "Codigo Matricula", DISCIPLINA.PK_CD_DISCIPLINA as "Codigo Disciplina", DISCIPLINA.NM_DISCIPLINA as "Disciplina",TURMA.NM_TURMA
  FROM MATRICULA
    INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
  INNER JOIN DISCIPLINA ON DISCIPLINA.FKI_CD_TURMA  = TURMA.PK_CD_TURMA
    WHERE DISCIPLINA.NM_DISCIPLINA =  @FILTRO

     ELSE	
	 
	 SELECT  MATRICULA.NM_ALUNOM, MATRICULA.PK_CD_MATRICULA as "Codigo Matricula", DISCIPLINA.PK_CD_DISCIPLINA as "Codigo Disciplina", DISCIPLINA.NM_DISCIPLINA as "Disciplina",TURMA.NM_TURMA
  FROM MATRICULA
    INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
  INNER JOIN DISCIPLINA ON DISCIPLINA.FKI_CD_TURMA  = TURMA.PK_CD_TURMA
    WHERE DISCIPLINA.NM_DISCIPLINA =  @FILTRO
	
   
END
GO


CREATE PROCEDURE SELECIONA_AVALIATIONL
     @FILTRO VARCHAR(100) 
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT  MATRICULA.NM_ALUNOM as "Nome Aluno", MATRICULA.PK_CD_MATRICULA as "Codigo Matricula", DISCIPLINA.PK_CD_DISCIPLINA as "Codigo Disciplina",AVALIATION.FREQUNCIA as Presença, DISCIPLINA.NM_DISCIPLINA as "Disciplina", AVALIATION.PK_CD_AVALIATION as "Codigo Avaliação", AVALIATION.DAT
  FROM MATRICULA
  INNER JOIN AVALIATION ON MATRICULA.PK_CD_MATRICULA = FKI_CD_MATRICULA
   INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
  INNER JOIN DISCIPLINA ON DISCIPLINA.PK_CD_DISCIPLINA  = AVALIATION.FKI_CD_DISCIPLINA
  WHERE DISCIPLINA.NM_DISCIPLINA =  @FILTRO 
     ELSE      
        
  SELECT  MATRICULA.NM_ALUNOM as "Nome Aluno", MATRICULA.PK_CD_MATRICULA as "Codigo Matricula", DISCIPLINA.PK_CD_DISCIPLINA as "Codigo Disciplina",AVALIATION.FREQUNCIA as Presença, DISCIPLINA.NM_DISCIPLINA as "Disciplina", AVALIATION.PK_CD_AVALIATION as "Codigo Avaliação", AVALIATION.DAT
  FROM AVALIATION
  INNER JOIN MATRICULA ON MATRICULA.PK_CD_MATRICULA = FKI_CD_MATRICULA
   INNER JOIN DISCIPLINA ON DISCIPLINA.PK_CD_DISCIPLINA  = AVALIATION.FKI_CD_DISCIPLINA
  WHERE DISCIPLINA.NM_DISCIPLINA =  @FILTRO
END
GO

CREATE  TABLE TIPO(
    PK_CD_TIPO VARCHAR(60) NOT NULL,
	NOME_TIP VARCHAR (60)NOT NULL,
	
	CONSTRAINT PK_CD_TIPO PRIMARY KEY(PK_CD_TIPO),
	
)
GO 
	INSERT INTO TIPO VALUES('COORDENADOR','COORDENADOR')
   INSERT INTO TIPO VALUES('SECRETARIA','SECRETARIA')
   INSERT INTO TIPO VALUES('PROFESSOR','PROFESSOR')
   INSERT INTO TIPO VALUES('ALUNO','ALUNO')
GO

 CREATE   TABLE CRIAR_LOGIN
(
	PK_CD_LOGIN INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR (60)UNIQUE NOT NULL,
	SENHA VARCHAR (60) NOT NULL,
	FK_CD_TIPO VARCHAR(60) NOT NULL,
	MAT_LOG INT NULL,
	CONSTRAINT PK_CD_LOGIN PRIMARY KEY(PK_CD_LOGIN),
	CONSTRAINT FK_CD_TIPO FOREIGN KEY(FK_CD_TIPO) REFERENCES TIPO(PK_CD_TIPO)
	
)
GO
	INSERT INTO CRIAR_LOGIN VALUES('SECRETARIA',1234,'SECRETARIA',0)
	INSERT INTO CRIAR_LOGIN VALUES('COORDENADOR',1234,'COORDENADOR',0)
	INSERT INTO CRIAR_LOGIN VALUES('M_LIMA',1234,'ALUNO',1)
	INSERT INTO CRIAR_LOGIN VALUES('R_SOUZA',1234,'PROFESSOR',1)
		
	
GO

CREATE PROCEDURE SP_LOGAR
@NOME VARCHAR(60),
@SENHA VARCHAR(60)
AS
SELECT FK_CD_TIPO,NOME,SENHA,PK_CD_LOGIN,MAT_LOG FROM CRIAR_LOGIN
WHERE NOME = @NOME AND SENHA = @SENHA

GO

CREATE PROCEDURE SP_BUCAR_LOGIN
@NOME VARCHAR(60)
AS SELECT PK_CD_LOGIN, NOME,L.NOME,T.PK_CD_TIPO,NOME_TIP AS TIPO FROM CRIAR_LOGIN L, TIPO T
WHERE T.PK_CD_TIPO = L.FK_CD_TIPO AND NOME LIKE'%'+ @NOME +'%'
GO
 
CREATE PROCEDURE SP_LISTA_LOGIN
@NOME VARCHAR(60)
AS 
SELECT PK_CD_LOGIN, NOME,L.NOME,T.PK_CD_TIPO,NOME_TIP AS TIPO FROM CRIAR_LOGIN L, TIPO T
WHERE T.PK_CD_TIPO = L.FK_CD_TIPO  ORDER BY PK_CD_LOGIN

GO
CREATE PROCEDURE INSERE_LOGIN
     @PK_CD_LOGIN INT OUTPUT,
     @NOME VARCHAR(60),
	 @SENHA VARCHAR(60),
	 @FK_CD_TIPO VARCHAR(60),
	 @MAT_LOG INT NULL
AS

     INSERT INTO CRIAR_LOGIN(NOME,SENHA,FK_CD_TIPO,MAT_LOG)
     VALUES(@NOME,@SENHA,@FK_CD_TIPO,@MAT_LOG)

     SET @PK_CD_LOGIN = (SELECT @@IDENTITY)
GO 

CREATE  PROCEDURE ALTERAR_LOGIN
     @PK_CD_LOGIN INT OUTPUT,
     @NOME VARCHAR(60),
	 @SENHA VARCHAR(60),
	 @FK_CD_TIPO VARCHAR(60)
	 
AS

     UPDATE CRIAR_LOGIN 
     SET 
		 NOME = @NOME,
		 SENHA = @SENHA,
		 FK_CD_TIPO = @FK_CD_TIPO
	
     WHERE PK_CD_LOGIN = @PK_CD_LOGIN 
GO

CREATE PROCEDURE EXCLUI_LOGIN
     @PK_CD_LOGIN INT -- INTPUT
AS    
     DELETE FROM CRIAR_LOGIN
     WHERE PK_CD_LOGIN = @PK_CD_LOGIN
	
GO

CREATE  PROCEDURE SELECIONA_LOGIN
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM CRIAR_LOGIN
		
	     ELSE 
	    SELECT CRIAR_LOGIN.PK_CD_LOGIN AS "CODIGO" ,CRIAR_LOGIN.NOME AS "USUARIO", CRIAR_LOGIN.SENHA, CRIAR_LOGIN.FK_CD_TIPO AS "TIPO", CRIAR_LOGIN.MAT_LOG AS "CODIGO DA MATRICULA" FROM CRIAR_LOGIN
        WHERE NOME LIKE '%' + @FILTRO + '%'
          
           
END

GO


CREATE TABLE NOTA_ALUNO
(
	PK_CD_NOTA INT IDENTITY(1,1) NOT NULL,
	 NOTA FLOAT NOT NULL,
	 DAT DATETIME NOT NULL,
	 FKII_CD_MATRICULA INT NOT NULL,
	 FKIII_CD_DISCIPLINA INT NOT NULL,
	CONSTRAINT PK_CD_NOTA PRIMARY KEY(PK_CD_NOTA),
	CONSTRAINT FKII_CD_MATRICULA FOREIGN KEY(FKII_CD_MATRICULA) REFERENCES MATRICULA(PK_CD_MATRICULA),
	CONSTRAINT FKIII_CD_DISCIPLINA FOREIGN KEY(FKIII_CD_DISCIPLINA) REFERENCES DISCIPLINA(PK_CD_DISCIPLINA)
)
GO

INSERT INTO NOTA_ALUNO VALUES (8,'2023-11-11',1,1)
GO

CREATE PROCEDURE INSERE_NOTA
     @PK_CD_NOTA INT OUTPUT,
	 @NOTA FLOAT ,
	 @DAT DATETIME ,
	 @FKII_CD_MATRICULA INT,
	 @FKIII_CD_DISCIPLINA INT
	 
AS

     INSERT INTO NOTA_ALUNO(NOTA,DAT,FKII_CD_MATRICULA,FKIII_CD_DISCIPLINA )
     VALUES(@NOTA,@DAT,@FKII_CD_MATRICULA,@FKIII_CD_DISCIPLINA)

     SET @PK_CD_NOTA = (SELECT @@IDENTITY)

GO


CREATE PROCEDURE ALTERA_NOTA
     @PK_CD_NOTA INT OUTPUT,
	 @NOTA FLOAT,
	 @DAT DATETIME,
	 @FKII_CD_MATRICULA INT,
	 @FKIII_CD_DISCIPLINA INT
	 
AS

     UPDATE NOTA_ALUNO 
     SET NOTA = @NOTA,
		 DAT = @DAT
		
     WHERE PK_CD_NOTA = @PK_CD_NOTA

GO

CREATE PROCEDURE EXCLUI_NOTA
	  @PK_CD_NOTA INT
	 
AS    
     DELETE FROM NOTA_ALUNO
     WHERE PK_CD_NOTA =@PK_CD_NOTA
GO
 
CREATE  PROCEDURE SELECIONA_NOTA
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO  IS NULL
        SELECT * FROM NOTA_ALUNO
		
     ELSE  
	SELECT  MATRICULA.NM_ALUNOM, MATRICULA.PK_CD_MATRICULA as "Codigo Matricula", DISCIPLINA.PK_CD_DISCIPLINA as "Codigo Disciplina", DISCIPLINA.NM_DISCIPLINA as "Disciplina",TURMA.NM_TURMA
  FROM MATRICULA
    INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
  INNER JOIN DISCIPLINA ON DISCIPLINA.FKI_CD_TURMA  = TURMA.PK_CD_TURMA
    WHERE DISCIPLINA.NM_DISCIPLINA =  @FILTRO
       
           
END
GO
CREATE PROCEDURE SELECIONA_NOTAL
     @FILTRO VARCHAR(100) = NULL
AS 
BEGIN
     IF @FILTRO  IS NULL
        SELECT * FROM NOTA_ALUNO
		 
     ELSE  
	 SELECT  MATRICULA.NM_ALUNOM as "Nome Aluno", MATRICULA.PK_CD_MATRICULA as "Codigo Matricula", DISCIPLINA.PK_CD_DISCIPLINA as "Codigo Disciplina", DISCIPLINA.NM_DISCIPLINA as "Disciplina", NOTA_ALUNO.PK_CD_NOTA as "CODIGO NOTA ", NOTA_ALUNO.NOTA AS NOTA, NOTA_ALUNO.DAT AS "DATA"
  FROM MATRICULA
  INNER JOIN NOTA_ALUNO ON MATRICULA.PK_CD_MATRICULA = NOTA_ALUNO.FKII_CD_MATRICULA
   INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
  INNER JOIN DISCIPLINA ON DISCIPLINA.PK_CD_DISCIPLINA  = NOTA_ALUNO.FKIII_CD_DISCIPLINA
   WHERE DISCIPLINA.NM_DISCIPLINA =  @FILTRO
       
           
END
GO
 
   CREATE PROCEDURE FILTRO_AVALIATION
     @FILTRO VARCHAR(100) = NULL,
	 @NM_DISC VARCHAR(100)
AS 
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM AVALIATION
     ELSE      
			SELECT  MATRICULA.NM_ALUNOM AS "NOME ALUNO",   DISCIPLINA.NM_DISCIPLINA as "NOME DA DISCIPLINA", AVALIATION.FREQUNCIA AS PRESENÇA, AVALIATION.DAT AS "DATA"
     FROM MATRICULA
   INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
   INNER JOIN DISCIPLINA ON DISCIPLINA.FKI_CD_TURMA  = TURMA.PK_CD_TURMA
  INNER JOIN AVALIATION ON MATRICULA.PK_CD_MATRICULA = FKI_CD_MATRICULA
     WHERE MATRICULA.PK_CD_MATRICULA = @FILTRO AND MATRICULA.PK_CD_MATRICULA = AVALIATION.FKI_CD_MATRICULA 
   AND   AVALIATION.FKI_CD_DISCIPLINA = DISCIPLINA.PK_CD_DISCIPLINA  AND DISCIPLINA.NM_DISCIPLINA = @NM_DISC
END
GO

  CREATE PROCEDURE FILTRO_NOTA
     @FILTRO VARCHAR(100) = NULL,
	 @NM_DISC VARCHAR(100)
AS	
BEGIN
     IF @FILTRO IS NULL
        SELECT * FROM NOTA_ALUNO
     ELSE      
         SELECT  MATRICULA.NM_ALUNOM AS "NOME ALUNO", DISCIPLINA.NM_DISCIPLINA as "NOME DISCIPLINA", NOTA_ALUNO.NOTA, NOTA_ALUNO.DAT "DATA"
     FROM MATRICULA
   INNER JOIN TURMA ON TURMA.PK_CD_TURMA = MATRICULA.FK_CD_TURMA
  INNER JOIN DISCIPLINA ON DISCIPLINA.FKI_CD_TURMA  = TURMA.PK_CD_TURMA
  INNER JOIN NOTA_ALUNO ON NOTA_ALUNO.FKII_CD_MATRICULA = MATRICULA.PK_CD_MATRICULA
   WHERE MATRICULA.PK_CD_MATRICULA = @FILTRO AND MATRICULA.PK_CD_MATRICULA = NOTA_ALUNO.FKII_CD_MATRICULA 
   AND   NOTA_ALUNO.FKIII_CD_DISCIPLINA = DISCIPLINA.PK_CD_DISCIPLINA AND DISCIPLINA.NM_DISCIPLINA = @NM_DISC
           
END
GO